FROM node:16-alpine AS build

ARG VUE_APP_API_URL=/api

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginxinc/nginx-unprivileged:1.27-alpine

ENV NGINX_SERVER_NAME=localhost
ENV NGINX_BACKEND_ADDRESS=http://backend:8081/

USER nginx

COPY --from=build /app/dist /usr/share/nginx/html/momo-store

HEALTHCHECK CMD curl --fail http://localhost:8080/ || exit 1

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
