services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - backend
    cap_drop:
      - ALL
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 1G
        reservations:
          cpus: 0.5
          memory: 512M

  frontend: 
    depends_on:
      backend:
        condition: service_healthy
    build: ./frontend
    restart: unless-stopped
    container_name: frontend
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_BACKEND_ADDRESS: http://backend:8081/
    ports: 
      - 80:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - frontend
      - backend
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    deploy:
      resources:
        limits:
          cpus: 0.5
          memory: 512M 
        reservations:
          cpus: 0.25
          memory: 256M

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
    internal: true